#!/usr/bin/env node
/**
 * Build every non-default site design next to the default one, so a reader can switch
 * designs on the live site (functions/_middleware.js serves the one their cookie picks).
 *
 * Runs after `astro build` has put the DEFAULT design in dist/ (see `npm run build`):
 *   1. for each other design D: PUBLIC_DESIGN=D astro build --outDir .design-builds/D
 *   2. copy its HTML pages to dist/_designs/D/<same path>, and its hashed _astro/ assets
 *      into dist/_astro/ (hashes differ per build, so nothing collides)
 *   3. write functions/design-pages.generated.js — the exact pages each design has, so the
 *      function only swaps in a page that exists (this site answers unknown URLs with a
 *      200 fallback page, so "fetch it and see" would silently serve the wrong page)
 *
 * Fails the build if any design ends up with a different set of pages than the default.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');
const TMP = path.join(ROOT, '.design-builds');
const OUT_JS = path.join(ROOT, 'functions', 'design-pages.generated.js');

// DESIGNS and the default live in src/consts.ts; read them from there so there is one list.
const consts = fs.readFileSync(path.join(ROOT, 'src/consts.ts'), 'utf8');
const DESIGNS = JSON.parse(
	consts.match(/export const DESIGNS = (\[[^\]]*\])/)[1].replace(/'/g, '"'),
);
const DEFAULT = consts.match(/export const DESIGN: Design = \(requested as Design\) \|\| '(\w+)'/)[1];
if (process.env.PUBLIC_DESIGN && process.env.PUBLIC_DESIGN !== DEFAULT) {
	console.error(`build-designs: dist/ was built as "${process.env.PUBLIC_DESIGN}", not the default "${DEFAULT}". Unset PUBLIC_DESIGN.`);
	process.exit(1);
}

function walk(dir, rel = '') {
	const out = [];
	for (const e of fs.readdirSync(path.join(dir, rel), { withFileTypes: true })) {
		const r = path.join(rel, e.name);
		if (e.isDirectory()) out.push(...walk(dir, r));
		else out.push(r);
	}
	return out;
}
const htmlPages = (dir) =>
	walk(dir)
		.filter((f) => f.endsWith('.html') && !f.startsWith('_designs'))
		.sort();
// dist-relative html file -> the URL path a reader requests
const urlOf = (f) => '/' + f.replace(/\\/g, '/').replace(/(^|\/)index\.html$/, '$1');

const defaultPages = htmlPages(DIST);
if (!defaultPages.length) {
	console.error('build-designs: dist/ has no pages — run astro build first.');
	process.exit(1);
}
fs.rmSync(path.join(DIST, '_designs'), { recursive: true, force: true });
fs.rmSync(TMP, { recursive: true, force: true });

const pages = {};
for (const d of DESIGNS.filter((x) => x !== DEFAULT)) {
	const out = path.join(TMP, d);
	console.log(`build-designs: building "${d}"…`);
	execFileSync('npx', ['astro', 'build', '--outDir', out], {
		cwd: ROOT,
		env: { ...process.env, PUBLIC_DESIGN: d },
		stdio: ['ignore', 'ignore', 'inherit'],
	});
	const built = htmlPages(out);
	const missing = defaultPages.filter((p) => !built.includes(p));
	const extra = built.filter((p) => !defaultPages.includes(p));
	if (missing.length || extra.length) {
		console.error(`build-designs: "${d}" pages differ from "${DEFAULT}". missing: ${missing.join(', ') || '—'} · extra: ${extra.join(', ') || '—'}`);
		process.exit(1);
	}
	for (const f of built) {
		const dest = path.join(DIST, '_designs', d, f);
		fs.mkdirSync(path.dirname(dest), { recursive: true });
		fs.copyFileSync(path.join(out, f), dest);
	}
	for (const f of walk(path.join(out, '_astro'))) {
		const dest = path.join(DIST, '_astro', f);
		if (!fs.existsSync(dest)) {
			fs.mkdirSync(path.dirname(dest), { recursive: true });
			fs.copyFileSync(path.join(out, '_astro', f), dest);
		}
	}
	pages[d] = built.filter((f) => f !== '404.html').map(urlOf);
	console.log(`build-designs: "${d}" → dist/_designs/${d}/ (${built.length} pages)`);
}
fs.rmSync(TMP, { recursive: true, force: true });

fs.mkdirSync(path.dirname(OUT_JS), { recursive: true });
fs.writeFileSync(
	OUT_JS,
	`// GENERATED by scripts/build-designs.mjs on every build — do not edit, do not commit.\n` +
		`export const DEFAULT = ${JSON.stringify(DEFAULT)};\n` +
		`export const DESIGNS = ${JSON.stringify(DESIGNS)};\n` +
		`export const PAGES = ${JSON.stringify(Object.fromEntries(Object.entries(pages).map(([d, p]) => [d, p])))};\n`,
);
console.log(`build-designs: wrote ${path.relative(ROOT, OUT_JS)} (default "${DEFAULT}", ${Object.keys(pages).length} alternates)`);
