import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

const blog = defineCollection({
	// Load Markdown and MDX files in the `src/content/blog/` directory.
	loader: glob({ base: './src/content/blog', pattern: '**/*.{md,mdx}' }),
	// Type-check frontmatter using a schema
	schema: ({ image }) =>
		z.object({
			title: z.string(),
			description: z.string(),
			// A one-sentence "what problem am I solving", shown in a callout at the very
			// top of the post (below the title, above the body). Optional but expected.
			problem: z.string().optional(),
			// Transform string to Date object
			pubDate: z.coerce.date(),
			updatedDate: z.coerce.date().optional(),
			heroImage: z.optional(image()),
			tags: z.array(z.string()).default([]),
			// How AI was involved in writing this post. Rendered as a badge at the
			// top of every post. Defaults to fully hand-written so nothing is ever
			// silently mislabeled.
			aiUsage: z
				.enum(['handwritten', 'dictated', 'assisted', 'ai-written'])
				.default('handwritten'),
			// Optional: makes this a "link post" (linkblog style). When set, the
			// title links out to this URL and the post still gets its own permalink.
			link: z.string().url().optional(),
			// Optional: binds this post into a named series with a shared ethos.
			// Rendered by SeriesNav (a thesis banner up top, the ordered parts list
			// at the bottom). Parts are derived from every post sharing `name`.
			series: z
				.object({
					name: z.string(),
					part: z.number(),
				})
				.optional(),
			// Build receipt pulled from the Claude Code session that authored the
			// post (scripts/session-telemetry.mjs). Reviewed before it ships,
			// rendered as a footer. Numbers are scoped to the authoring window.
			telemetry: z
				.object({
					model: z.string(),
					ccVersion: z.string().optional(),
					liveAfterMin: z.number(),
					redeploys: z.number().default(0),
					instructions: z.number(),
					turns: z.number(),
					toolCalls: z.number(),
					compacts: z.number().default(0),
					phoneRelayed: z.boolean().default(false),
				})
				.optional(),
			// An independent AI-text detector's reading (Pangram), generated by
			// scripts/pangram-scores.mjs and run on the PROSE only. Shown as a badge
			// next to `aiUsage`. The two measure different things: `aiUsage` is my own
			// call on how the piece was MADE (how much I directed vs wrote); this is
			// what a detector reads off the finished TEXT. They can disagree, and the
			// pairing is the point. Percentages are 0-100.
			pangram: z
				.object({
					verdict: z.string(),
					human: z.number(),
					assisted: z.number(),
					ai: z.number(),
					model: z.string(),
					checkedOn: z.string(),
				})
				.optional(),
		}),
});

export const collections = { blog };
